[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FinaleTools"
version = "0.0.2"
authors = [
    {name="James Li", email="jameswli2021@gmail.com"},
    {name="Yaping Liu", email="yaping.liu@cchmc.org"},
]
description = "A package containing functions to process paired-end reads of cfDNA fragment WGS."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pysam",
]

[project.urls]
"Homepage" = "https://epifluidlab.github.io"