[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FinaleTools"
version = "0.0.0"
authors = [
    { name="James Li", email="jameswli2021@gmail.com"}
]
description = "A package containing functions to process paired-end reads of cfDNA fragment WGS."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://epifluidlab.github.io"